### ISSUE TITLE
License not yet defined

### ISSUE THREAD

**Issue by fox2k06** [tiagocoutinho/modbus-proxy-rs#1]
_First of all, congratulations on this great project. Flawlessly solves a very common problem with Modbus/TCP connections.
Thanks a lot for this._

One thing is missing: Could you please specify a license for your project?

_Not completely altruistic I would wish for a very free one à la MIT ;) of course it is up to you_

**Comment by daolis** [comment]
Licence would be cool!
The MIT the better ;-)

Thanks a lot too!

**Comment by daolis** [comment]
@fox2k06 JFYI Found this...
https://github.com/tiagocoutinho/modbus-proxy-rs/blob/master/Cargo.toml#L13

**Comment by fox2k06** [comment]
thanks for staying on the issue and finding the license 👏
